root/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index')->name('home');
Route::resource('/products', 'ProductController');
Route::delete('/deleteall', 'ProductController@deleteall');
Route::resource('/inventory', 'DailyMISController');
Route::resource('/generate', 'ReportGenerator');
Route::post('/process/generate/', 'ReportGenerator@process')->name('process-generator');
Route::resource('/settings', 'SettingController');
Route::get('/update-inventory', 'HomeController@UpdateInventory')->name('update-inventory');
Route::resource('/account', 'UserController');

Auth::routes();

root/resources/views/generator.blade.php
@extends('layouts.app')
@section('title',"Create Product")
@section('content')

<div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-10">
            <h5 class="title">Report Generator {{Carbon::today()->toFormattedDateString()}}</h5>
            </div>
            <div class="col-sm-12 col-md-2 text-right">
                
            </div>
        </div>
    <hr>  
    <div class="row">
        <div class="col-sm-12 col-md-4">
            <form action="{{route('generate.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="sales">Sales CSV</label>
                    <input type="file" name="sales" id="sales">
                    <a href="/sales.csv" class="text-danger" download>Download Sample File</a>
                </div>
                <div class="py-2"></div>
                <div class="form-group">
                    <label for="amazon_stock">Amazon Stock CSV</label>
                    <input type="file" name="amazon_stock" id="amazon_stock">
                    <a href="/fba.csv" class="text-danger" download>Download Sample File</a>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success">Generate Report</button>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

root/resources/views/home.blade.php
@extends('layouts.app')
@section('title',"Dashboard")
@section('content')
<div class="container">

</div>
@endsection

root/resources/views/profile.blade.php
@extends('layouts.app')
@section('title',"$user->name's Profile")
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-10">
                <h5 class="title">Edit Profile</h5>
            </div>
            <div class="col-sm-12 col-md-2 text-right">
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-12 col-md-4">
                <form action="{{route('account.update',[$user])}}" method="post">
                    @csrf
                    <input type="hidden" name="_method" value="PUT">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" name="name" id="name" class="form-control" value="{{$user->name}}">
                    </div>
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" name="username" id="username" class="form-control" value="{{$user->username}}">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email" class="form-control" value="{{$user->email}}">
                    </div>
                    <div class="form-group">
                        <label for="password">Change Password</label>
                        <input type="password" name="password" id="password" class="form-control">
                    </div>
                    <div class="form-group">
                       <button type="submit" class="btn btn-outline-success">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

root/resources/views/select-options.blade.php
@extends('layouts.app')
@section('title',"Settings")
@section('content')
<div class="container">
    <div class="row">
        <form class="col-sm-12 col-md-12" action="{{route('process-generator')}}" method="POST">
            @csrf
            <strong>Select Options to Process on Sale</strong>
            <br/>
            @foreach ($sortItems as $item)
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" name="sorter[{{$item}}]" checked value="{{$item}}" id="sorter-{{$item}}">
                    <label class="custom-control-label" for="sorter-{{$item}}">{{$item}}</label>
                </div>
            @endforeach
            <br/>            
            <textarea type="hidden" name="data" class="d-none">
                    {{json_encode($data)}}
            </textarea>
            <textarea type="hidden" name="amazon" class="d-none">
                    {{json_encode($amazon)}}
            </textarea>
            <ul class="bg-danger text-white">
                @php
                    $sol = 0;
                @endphp
                @foreach ($data as $item)
                    @if ($item['product'] == false)
                    @php
                        $sol++;
                    @endphp
                    @endif
                @endforeach      
                @if ($sol >= 1)
                    <div class="bg-danger p-2 text-white">
                        {{$sol}} Products are not Found on Database. Please create it from here and continue.
                    </div>
                @endif      
            </ul>
            <table class="table table-sm">
                <tbody>
                @foreach ($data as $item)
                    @if ($item['product'] == false)
                    <tr>
                        <td>{{$item['sku']}}</td>
                        <td>{{$item['quantity']}}</td>
                        <td>
                            <div class="form-group">
                                <label for="code_{{$item['sku']}}">Code</label>
                                <input type="text" required name="code[{{$item['sku']}}]" value="{{old('code'.$item['sku'])}}" id="code_{{$item['sku']}}" class="form-control form-control-sm">
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <label for="master_{{$item['sku']}}">Master QNTY</label>
                                <input type="text"  name="master[{{$item['sku']}}]" value="{{old('master'.$item['sku'])}}" id="master_{{$item['sku']}}" class="form-control form-control-sm">
                            </div>
                        </td>
                    </tr>
                    {{-- @else
                    <tr>
                        <td>{{$item['sku']}}</td>
                        <td>{{$item['quantity']}}</td>
                        <td>{{$item['code']}}</td>
                        <td>{{$item['master']}}</td>
                    </tr> --}}
                    @endif
                @endforeach
                </tbody>
            </table>
            <div class="form-group py-4">
                <button type="submit" class="btn btn-success">Continue</button>
            </div>
        </form>
    </div>
</div>
@endsection

root/resources/views/update-inventory.blade.php
@extends('layouts.app')
@section('title',"Update Inventory")
@section('content')

<div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-10">
            <h5 class="title">UPDATE INVENTORY {{Carbon::today()->toFormattedDateString()}}</h5>
            </div>
            <div class="col-sm-12 col-md-2 text-right">
                <a href="/updateinventory.csv" class="btn btn-sm btn-danger" download>Download Sample File</a>
            </div>
        </div>
        <hr>  
<div class="row">
    <div class="col-sm-12 col-md-4">
        <form method="POST" action="{{route('inventory.update',0)}}" enctype="multipart/form-data">
            @csrf
            <input type="hidden" name="_method" value="PUT">
            <div class="form-group">
                <label for="date">Date of Inventory Update</label>
            <input type="text" readonly name="date" id="date" class="form-control date-picker" value="{{Carbon::today()->toDateString()}}">
            </div>
            <div class="form-group">
                <label for="upload">Upload</label>
                <input type="file" name="upload" id="upload" class="form-control">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Upload</button>
            </div>
        </form>
    </div>    
</div>        
</div>
@endsection

root/resources/views/verification.blade.php
@extends('layouts.app')
@section('title',"Data Generator")
@section('content')
    <div class="container">
        <div class="p-2 bg-danger text-white">
            <strong>
                The system is unable to find a product with the SKU's : 
                @foreach ($data as $item) @if ($item->code == "Product not Available"){{$item->sku}} @endif @endforeach                
            </strong>
            <br/>
            To continue, please enter the Code and Master Quantity to create product and generate the reports
        </div>
        <form action="{{route('process-generator')}}" method="post" class="form">
            @csrf
            <textarea type="hidden" name="data" class="d-none">
                    {{json_encode($data)}}
            </textarea>
            <table class="table table-sm">
                <thead class="table-dark">
                    <tr>
                        <th>SKU</th>
                        <th>QTY</th>
                        <th>CODE</th>
                        <th>MASTER QTY</th>
                    </tr>
                </thead>
                <tbody>
                @foreach ($data as $item)
                    @if ($item->code == "Product not Available")
                    <tr class="bg-danger text-white">
                        <td>{{$item->sku}}</td>
                        <td>{{$item->quantity}}</td>
                        <td>
                            <div class="form-group">
                                <input type="text" required name="code[{{$item->sku}}]" value="{{old('code'.$item->sku)}}" id="code_{{$item->sku}}" class="form-control form-control-sm">
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <input type="text"  name="master[{{$item->sku}}]" value="{{old('master'.$item->sku)}}" id="master_{{$item->sku}}" class="form-control form-control-sm">
                            </div>
                        </td>
                    </tr>
                    @else
                    <tr>
                        <td>{{$item->sku}}</td>
                        <td>{{$item->quantity}}</td>
                        <td>{{$item->code}}</td>
                        <td>{{$item->master}}</td>
                    </tr>
                    @endif
                @endforeach
                </tbody>
            </table>
            <button class="btn btn-success" type="submit">Save</button>
        </form>
    </div>
@endsection