root/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index')->name('home');
Route::resource('/products', 'ProductController');
Route::delete('/deleteall', 'ProductController@deleteall');
Route::resource('/inventory', 'DailyMISController');
Route::resource('/generate', 'ReportGenerator');
Route::post('/process/generate/', 'ReportGenerator@process')->name('process-generator');
Route::resource('/settings', 'SettingController');
Route::get('/update-inventory', 'HomeController@UpdateInventory')->name('update-inventory');
Route::resource('/account', 'UserController');

Auth::routes();

root/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public function Mis()
    {
        return $this->hasMany('App\DailyMIS','product','code');
    }
}

root/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Product;
use Illuminate\Http\Request;
use League\Csv\Reader;

class ProductController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // Arrays and Qs 
        $paginatables = [5,10,20,30,40,50];
        $page = $paginatables[0];
        $query = ['user'=>$request->user()->id];

        // Filters
        if($request->counts){
            $page = $request->counts;
        }
        if($request->sortby){
            
        }
        if($request->search){
            $query[] = ['SKU','LIKE',"%$request->search%"];
        }
        
        $products = Product::where($query)->paginate($page);

        // return $products;
        return view('products.index',['products'=>$products,'request'=>$request,'paginatables'=>$paginatables]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'SKU'=>'unique:products|required_without_all:upload',
            'code'=>'required_without_all:upload',
            'upload'=>'required_without_all:SKU,code',
        ];
        $messages = [
            'upload.required_without_all'=>"We need a valid File",
            'SKU.required_without_all'=>'We Need an SKU!',
            'code.required_without_all'=>'We Need an Product Code'
        ];
        $request->validate($rules,$messages);

        if($request->hasfile('upload')){
            $csv = Reader::createFromPath($request->file('upload'), 'r');
            $csv->setHeaderOffset(0);
            $created = 0;
            $uploaded = 0;
            foreach ($csv as $key) {
                $uploaded++;
                $sku    = (isset($key['SKU'])) ? $key['SKU']:$key['sku'];
                $code    = (isset($key['CODE'])) ? $key['CODE']:$key['code'];
                $product = Product::where(['user'=>$request->user()->id,'SKU'=>$sku])->first();
                if(!$product){
                    $product = new Product;
                    $product->SKU   = $sku;
                    $product->code  = $code;
                    $product->user  = Auth::user()->id;
                    $product->save();
                    $created++;
                }
            }
            return redirect()->back()->with(['success'=>"Created $created products from $uploaded uploaded products"]);
        }
        else{
            $product = Product::where(['user'=>$request->user()->id,'SKU'=>$request->SKU])->first();
            if($product){

            }
            else{
                $product = new Product;
            }
            $product->SKU   = $request->SKU;
            $product->code  = $request->code;
            $product->user  = Auth::user()->id;
            $product->save();
            return redirect()->back()->with(['success'=>"Created new Product $request->sku"]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.product',['product'=>$product]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product,Request $request)
    {
        $product->delete();
        return redirect()->back()->with(['success'=>'Deleted Product']);
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function deleteall(Request $request)
    {
        $ps = Product::all();
        foreach ($ps as $key) {
            $key->delete();
        }
        return redirect()->back()->with(['success'=>'All Products Deleted']);
    }
}

root/resources/views/products/create.blade.php
@extends('layouts.app')
@section('title',"Create Product")
@section('content')

<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-10">
            <h1 class="">Create Product</h1>
        </div>
        <div class="col-sm-12 col-md-2 text-right">
            <a href="{{route('products.index')}}" class="btn btn-outline-secondary">Back </a>
        </div>
    </div>
    <hr>  
    <div class="row">
        <div class="col-sm-12 col-md-4">
            <form action="{{route('products.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="SKU">SKU</label>
                    <input type="text" name="SKU" id="SKU" class="form-control">
                </div>
                <div class="form-group">
                    <label for="code">Product Code</label>
                    <input type="text" name="code" id="code" class="form-control">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success btn-sm">Save</button>
                </div>
            </form>
        </div>
        <div class="col-sm-12 col-md-4 offset-md-2">
            <a href="/products.csv" class="text-danger" download>Download Sample File</a>
            <form action="{{route('products.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="upload">Upload CSV/TXT</label>
                    <input type="file" name="upload" id="upload" class="" accept=".txt,.csv">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success btn-sm">Save</button>
                </div>
            </form>
        </div>
    </div>  
</div>
@endsection

root/resources/views/products/index.blade.php
@extends('layouts.app')
@section('title',"Products")
@section('content')
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <h1 class="">Products</h1>
            <strong><i>{{$products->total()}} Total</i></strong>
        </div>
        <div class="col-sm-12 col-md-4 offset-md-2 text-right">
            <form action="/deleteall" method="POST" class="form form-sm" id="deleteForm" onsubmit="ProcessForm()">
                @csrf
                <a href="{{route('products.create')}}" class="btn btn-outline-primary">Create / Upload Product </a>
                <input type="hidden" name="_method" value="DELETE">
                <button class="btn btn-outline-danger " type="submit">Delete All Products</button>
            </form>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-sm-12 col-md-2 border-right">
            <form action="" class="form form-sm">
                <div class="form-group">
                    <label for="search">Search</label>
                    <input type="search" name="search" id="search" autocomplete="off" class="form-control" value="{{ $request->search }}">
                </div>
                <div class="form-group">
                    <label for="counts">Products to Show</label>
                    <select name="counts" id="counts" class="form-control form-control-sm">
                        @foreach ($paginatables as $paginatable)
                            <option @if($request->counts && $request->counts == $paginatable) selected @endif  value="{{$paginatable}}">{{$paginatable}}</option>
                        @endforeach
                    </select>
                </div>
                <button type="submit" class="btn btn-sm btn-secondary">Filter</button>
            </form>
        </div>
        <div class="col-sm-12 col-md-10">
            <div class=" p-4 bg-white">
                <table class="table table-sm">
                    <thead>
                    <tr>
                        <th>SKU</th>
                        <th>Code</th>
                        <th>Created on</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if($products->count() < 1)
                        <tr>
                            <th colspan="3" class="text-center">
                                No products found
                            </th>
                        </tr>
                    @else 
                        @foreach ($products as $product)
                        <tr>
                            <td><a href="{{route('products.show',[$product])}}">{{$product->SKU}}</a></td>
                            <td>{{$product->code}}</td>
                            <td>{{Carbon::parse($product->created_at)->toFormattedDateString()}}</td>
                            <td>
                                <form action="{{route('products.destroy',$product)}}" class="form-inline" method="post">
                                        @csrf
                                    <button class="btn py-0 btn-link text-danger">Delete</button>
                                    <input type="hidden" name="_method" value="delete">
                                </form>
                            </td>                        
                        @endforeach
                    @endif
                </tbody>
            </table>
            {{$products->appends(['counts' => $request->counts])->links()}}
        </div>
        </div>
    </div>
</div>
<script>
function ProcessForm() {
    var cf = confirm("Are you sure you want to reset the Products and remove all? \n This is not reversable.");
    if(cf){
        return true;
    }
    else{
        event.preventDefault();
    }
}
</script>
@endsection

root/resources/views/products/product.blade.php
@extends('layouts.app')
@section('title',"Products")
@section('content')
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <h1 class="">{{$product->SKU}}</h1>
        </div>
        <div class="col-sm-12 col-md-4 offset-md-2 text-right">

        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th>Updated On</th>
                        <th>Stock</th>
                        <th>Last Updated </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($product->Mis()->where('user',Auth::user()->id)->orderBy('mis_date','asc')->get() as $mis)
                        <tr>
                            <th>{{Carbon::parse($mis->mis_date)->toFormattedDateString()}}</th>
                            <th>{{$mis->stock}}</th>
                            <th>{{Carbon::parse($mis->updated_at)->diffForHumans()}}</th>
                        </tr>
                    @endforeach
                    @empty($product->Mis)
                        <tr>
                            <th colspan="2" class="text-center">No Records Updated.</th>
                        </tr>
                    @endempty
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection