root/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@index')->name('home');
Route::resource('/products', 'ProductController');
Route::delete('/deleteall', 'ProductController@deleteall');
Route::resource('/inventory', 'DailyMISController');
Route::resource('/generate', 'ReportGenerator');
Route::post('/process/generate/', 'ReportGenerator@process')->name('process-generator');
Route::resource('/settings', 'SettingController');
Route::get('/update-inventory', 'HomeController@UpdateInventory')->name('update-inventory');
Route::resource('/account', 'UserController');

Auth::routes();

root/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title') \ {{ config('app.name', 'Laravel') }} </title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark navbar-laravel py-0">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('products.index') }}">{{ __('Products') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('inventory.create') }}">
                                        {{ __('Import Inventory') }}
                                        @if (DailyMIS::misCheck())
                                        <i class="fas fa-check text-success"></i>
                                        @else
                                        <i class="fas fa-exclamation-circle text-danger"></i>
                                        @endif
                                    </a>
                                </li>
                                @if (DailyMIS::misCheck())
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('generate.index') }}">{{ __('Generate Reports') }}</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('update-inventory') }}">{{ __('Update Inventory') }}</a>
                                </li>
                                @endif
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('account.index') }}">{{ __('Edit Profile') }}</a>
                                    <a class="dropdown-item" href="{{ route('settings.index') }}">{{ __('Settings') }}</a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST">
                                            <button class="dropdown-item" type="submit">{{ __('Logout') }}</button>
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        @if (Session::has('success'))
            <div class="alert alert-success">
                <p> {!! Session::get('success') !!}</p>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{!! $error !!}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        @auth
        @if (!DailyMIS::misCheck())
            <div class="notice px-3 bg-danger text-white">
                <p class="py-1">
                    Please Upload your Daily MIS. You will not be able to Upload this after 11:59 PM Tonight
                    <a class="btn btn-sm btn-outline-white" href="{{ route('inventory.create') }}">Upload</a>
                </p>
            </div>            
        @endif
        @endauth
        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>